## Практическое задание к видеоуроку “Введение в линейную алгебру”

5.1.
Вектор – это частный случай матрицы 1хN и Nх1. Повторите материал для векторов, уделяя особое внимание умножению A∙B.
Вычислите, по возможности не используя программирование: (5Е)–1, где Е – единичная матрица размера 5х5

In [1]:
%%latex
\begin{eqnarray*}E=\left|\begin{array}{ccccc}1&0&0&0&0\\0&1&0&0&0\\0&0&1&0&0\\0&0&0&1&0\\0&0&0&0&1\end{array}\right|;\quad
5E=\left|\begin{array}{ccccc}5&0&0&0&0\\0&5&0&0&0\\0&0&5&0&0\\0&0&0&5&0\\0&0&0&0&5\end{array}\right|;\quad 5E^{-1}=\left|
    \begin{array}{ccccc}\frac{1}{5}&0&0&0&0\\0&\frac{1}{5}&0&0&0\\0&0&\frac{1}{5}&0&0\\0&0&0&\frac{1}{5}&0\\0&0&0&0&
    \frac{1}{5}\end{array}\right|\end{eqnarray*}

<IPython.core.display.Latex object>

5.2. Вычислите определитель: [[1, 2, 3], [4, 0, 6], [7, 8, 9]]

In [2]:
%%latex
\begin{eqnarray*}\left|\begin{array}{ccc}1&2&3\\4&0&6\\7&8&9\end{array}\right|;\quad \varDelta=-4*\left|\begin{array}{cc}2&3
\\8&9\end{array}\right|+0*\left|\begin{array}{cc}1&3\\7&9\end{array}\right| -6*\left|\begin{array}{cc}1&2\\7&8\end{array}
\right|=-4*(2*9-8*3)-6*(1*8-7*2)=60\end{eqnarray*}

<IPython.core.display.Latex object>

5.3.
1. Вычислите матрицу, обратную данной:
[[1, 2, 3], [4, 0, 6], [7, 8, 9]]
2. Приведите пример матрицы 4х4, ранг которой равен 1.

In [3]:
%%latex
\begin{eqnarray*}A=\left|\begin{array}{ccc}1&2&3\\4&0&6\\7&8&9\end{array}\right|;\quad М=\left|\begin{array}{ccc}
-48&-6&32\\-6&-12&-6\\12&-6&-8\end{array}\right|;\quad A_*^T=\left|\begin{array}{ccc}-48&6&12\\6&-12&6\\32&6&-8
\end{array}\right|;\quad A^{-1}=\frac{1}{60}*\left|\begin{array}{ccc}-48&6&12\\6&-12&6\\32&6&-8\end{array}\right|\end{eqnarray*}

<IPython.core.display.Latex object>

In [4]:
%%latex
\begin{eqnarray*}B=\left|\begin{array}{cccc}1&2&3&4\\2&4&6&8\\-1&-2&-3&-4\\4.5&9&13.5&18\end{array}\right|; \quad rang(B)=1
\end{eqnarray*}

<IPython.core.display.Latex object>

In [5]:
import numpy as np
B = np.array([[1, 2, 3, 4], [2, 4, 6, 8], [-1, -2, -3, -4], [4.5, 9, 13,5, 18]])
np.linalg.matrix_rank(B)

1

5.4.
Вычислите скалярное произведение двух векторов:  
(1, 5)  и  (2, 8)

In [6]:
%%latex
\begin{eqnarray*}
\overrightarrow{a}=(1, 5); \quad \overrightarrow{b}=(2, 8); \quad \overrightarrow{a}*\overrightarrow{b}=1*2+5*8=42
\end{eqnarray*}

<IPython.core.display.Latex object>

5.5
Вычислите смешанное произведение трех векторов:
(1, 5, 0), (2, 8, 7) и (7, 1.5, 3) 

In [7]:
%%latex
\begin{eqnarray*}
\overrightarrow{a}=(1, 5, 0); \quad \overrightarrow{b}=(2, 8, 7); \quad \overrightarrow{c}=(7, 1.5, 3); \quad
\overrightarrow{a}x\overrightarrow{b}=\left|\begin{array}{ccc}i&j&k\\1&5&0\\2&8&7\end{array}\right| \quad
(axb)_i=5*7-8*0; \quad (axb)_j=-(1*7-0*2); \quad (axb)_k=1*8-5*2; \quad \overrightarrow{a}x\overrightarrow{b}=(35, -7, -2);
\qquad \overrightarrow{a}x\overrightarrow{b}*\overrightarrow{c}=35*7+(-7*1.5)+(-2*3)=228.5
\end{eqnarray*}

<IPython.core.display.Latex object>

In [8]:
import numpy as np
a = np.array([1, 5, 0])
b = np.array([2, 8, 7])
c = np.array([7, 1.5, 3])
np.inner(np.cross(a, b), c)

228.5

## Практическое задание к видеоуроку “СЛАУ”

1. Решите линейную систему: [[1, 2, 3], [4, 0, 6], [7, 8, 9]]*X=[12, 2, 1]

In [9]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
B = np.array([12, 2, 1])
np.dot(np.linalg.inv(A), B)

array([-9.2       ,  0.9       ,  6.46666667])

2. Найдите псевдорешение:
x + 2y – z = 1
3x – 4y = 7
8x – 5y + 2z = 12
2x – 5z = 7
11x +4y – 7z = 15

In [10]:
A = np.array([[1, 2, -1], [3, -4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]])
B = np.array([1, 7, 12, 7, 15])
np.linalg.lstsq(A, B, rcond=None)

(array([ 1.13919353, -0.90498444, -0.9009803 ]),
 array([0.71523211]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))

3. Сколько решений имеет линейная система:
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]*X=[12, 2, 1]
Если ноль – то измените вектор правой части так, чтобы система стала совместной, и решите ее. 

In [11]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # матрица с линейной зависимостью строк
B = np.array([[12, 2, 1]])
C = np.concatenate((A, B.T), axis=1)
np.linalg.matrix_rank(A), np.linalg.matrix_rank(C) # СЛАУ несовместна

(2, 3)

In [12]:
B1 = np.array([[12, 24, 36]])
C1 = np.concatenate((A, B1.T), axis=1)
print('rang(A, C1) =', (np.linalg.matrix_rank(A), np.linalg.matrix_rank(C1)))
np.linalg.solve(A, *B1)

rang(A, C1) = (2, 2)


array([0., 0., 4.])

4. Вычислите LU-разложение матрицы:
[[1, 2, 3], [2, 16, 21], [4, 28, 73]]
После этого придумайте вектор правых частей и решите полученную линейную систему трех уравнений с данной матрицей.

In [13]:
import scipy.linalg

A = np.array([[1, 2, 3], [2, 16, 21], [4, 28, 73]])
PL, U = scipy.linalg.lu(A, permute_l=True)
B = np.array([13, 23, 9])
print(np.dot(np.linalg.inv(U), np.dot(np.linalg.inv(PL), B)))
print(np.dot(np.linalg.inv(A), B))

[14.02777778  1.06944444 -1.05555556]
[14.02777778  1.06944444 -1.05555556]


5. Найдите нормальное псевдорешение недоопределенной системы:
x + 2y – z = 1
8x – 5y + 2z = 12
Для этого определите функцию Q(x,y,z), равную норме решения, и найдите ее минимум.

In [14]:
import matplotlib.pyplot as plt
%matplotlib inline

def Q(x, y, z):
    return (x**2 + y**2 + z**2)

A = np.array([[1, 2, -1], [8, -5, 2]])
B = np.array([1, 12])
print(np.linalg.lstsq(A, B, rcond=None))

x = np.linspace(-2, 5, 701)
y = 10*x - 14
z = 21*x - 29
plt.plot(x, Q(x, y, z))
plt.grid()
plt.axis([-2, 5, -500, 6000])
plt.plot([1.38191882, 1.38191882], [0, 6000], color='black', linestyle='dashed');

(array([ 1.38191882, -0.18081181,  0.0202952 ]), array([], dtype=float64), 2, array([9.65316119, 2.41173777]))


6. Найдите одно из псевдорешений вырожденной системы:
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]*X=[2, 5, 11]
Попробуйте также отыскать и нормальное псевдорешение.

In [15]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[2, 5, 11]])
C = np.concatenate((A, B.T), axis=1)

print(f'rang(A, C) = {np.linalg.matrix_rank(A), np.linalg.matrix_rank(C)}')

Q, R = np.linalg.qr(A)
R1 = R[:2, :2]
B1 = np.dot(Q.T, *B)[:2]
print(f'X = {np.append(np.linalg.solve(R1, B1), 0)}')
print(np.linalg.lstsq(A, *B, rcond=None))

rang(A, C) = (2, 3)
X = [1.50000000e+00 9.45096256e-15 0.00000000e+00]
(array([ 1.25,  0.5 , -0.25]), array([], dtype=float64), 2, array([1.68481034e+01, 1.06836951e+00, 3.33475287e-16]))
